### ISSUE TITLE
Language Layers Wanted

### ISSUE THREAD

**Issue by a-schaefers** [a-schaefers/spartan-emacs#1]
I only mess with Bash and Python most of the time, so that's all there is.

Notice the Python layer doesn't have any dependencies other than eglot-- it includes debugging with pdb, a repl, a linter, intelligent auto completion, find definition, etc...

It only requires a user to do something like, `pip install --user pipenv && pipenv install --user python-language-server[all]` and they're done.

Eglot should make our language layers mostly batteries included!

Use as many Emacs builtins + Eglot (LSP) features as possible. That's the ideal.

**Comment by AndersonTorres** [comment]
Hello!

I think I can help adding something...

**Comment by a-schaefers** [comment]
Cool

**Comment by Ebert-Hanke** [comment]
Very interesting project! What is your opinion on company-mode? I think for a language layer to use with Rust it might be beneficial and the colors could be customised to fit the overall monochrome approach.

**Comment by a-schaefers** [comment]
Thanks.

Company mode is fine if it helps you, I tend to just hit M-/ to complete things though using Emacs built in or LSP.  I'd accept a PR of a company layer if it was well tested and clean code.

Same Rust.

**Comment by jgarte** [comment]
I prefer emacs built-in completion to company mode. I use it with eglot.

**Comment by a-schaefers** [comment]
I've recently added many.

**Comment by Ebert-Hanke** [comment]
Great work! Thank you!
... sorry for never sending that rust layer, the last year was very chaotic. Really appreciate the work you put into spartan-emacs!

**Comment by a-schaefers** [comment]
Just wanna let ya'll know, major updates here took place, worth a look if you still are using this setup @AndersonTorres  @Ebert-Hanke  @jgarte
