### ISSUE TITLE
[bug] after-init-hook and after-init 

### ISSUE THREAD

**Issue by bommbo** [a-schaefers/spartan-emacs#7]
Put "after-init" configuration in ~/.emacs.d/spartan.d/ does not work.  But put "after-init" configuration in spartan.el works.

eg: 
```
(add-hook 'after-init-hook 'global-display-fill-column-indicator-mode)
(setq-default fill-column 80)

(use-package doom-modeline
  :straight t
  :defer t
  :config
  :hook (after-init . doom-modeline-mode))
```

**Comment by a-schaefers** [comment]
Should be working. Taking a look, will test your exact code.

**Comment by a-schaefers** [comment]
Probably need to remove  :hook (after-init . doom-modeline-mode) because spartan.d is loaded from the after init hook already.

**Comment by a-schaefers** [comment]
yea remove that line

```
 :hook (after-init . doom-modeline-mode)
```

because spartan.d is loaded in the emacs-setup-hook which is after the after-init-hook give that a whirl

**Comment by a-schaefers** [comment]
Not a bug. Here you go.

```
(use-package doom-modeline
  :straight t
  :config
  (doom-modeline-mode 1))
```

No need to defer, it is last in the chain already in the emacs-setup-hook by default from being in spartan.d/

**Comment by bommbo** [comment]
I have already made the necessary changes to the code. I just want to know why.
```
(global-display-fill-column-indicator-mode 1)
(setq-default fill-column 80)

(use-package doom-modeline
  :straight t
  :init
  (doom-modeline-mode))
```

**Comment by a-schaefers** [comment]
The reason it didn't work with ` :hook (after-init . doom-modeline-mode)` is because the after-init code has already executed before spartan.d files are loaded. So that means your code doesn't run with that bit there.

**Comment by bommbo** [comment]
Thank you.
